### ISSUE TITLE
h5tovts error

### ISSUE THREAD

**Issue by paulakash24** [mtav/h5utils#1]
Hello,

I am trying to generate a .vts file from .h5 file using `h5tovts` command. My .h5 file contains CFD data.

command = `h5tovts filename.h5`

The command executes and shows me what is inside the hdf5 file but at the end it is not generating the .vts file.
I am getting this message at the end:

`raise Exception('Data of dimension {}. Only 3D data supported at the moment.'.format(len(data.shape))) Exception: Data of dimension 2. Only 3D data supported at the moment.`

The hdf5 file contains 60000 groups.Each group contains 4 datasets. The structure looks as given below:
```
/Time_9700               Group
/Time_9700/LatTyp        Dataset {501, 83}
/Time_9700/Rho           Dataset {501, 83}
/Time_9700/Ux            Dataset {501, 83}
/Time_9700/Uy            Dataset {501, 83}
```

Any help would be appreciated.

**Comment by paulakash24** [comment]
I am going through the source code, as far as I could get (and also from the error message), it seems the package does not support 2D datasets.  I would like to know if there are any workaround it for now..

Thanks

**Comment by mtav** [comment]
Hi,

Yes, 2D datasets are not supported yet, as I initially wrote the code for my own use on 3D structures.

But for 2D, you can use mpb-data and h5topng from the official h5utils MIT package.
Have a look here for example: https://mpb.readthedocs.io/en/latest/Data_Analysis_Tutorial/
This is the command to convert the data to an orthonormal basis (and show 3x3 periods of it):
`unix% mpb-data -r -m 3 -n 32 epsilon.h5`
